feat, added Notifier which implements basic fuctions
DD2480-group14/Assignment-2 pull request #12
Opened 2023-02-06 19:51 UTC by dengty1998

2023-02-06 20:01 UTC, aversey requested changes
"set" in the names of functions doesn't seem to be the right word. Don't forget to load secret token from a file (on path "./token"?) and to provide some way for passing the build status and related commit ID to your code (maybe through constructor or method "notify").

Overall, good work, keep up!

2023-02-06 20:01 UTC, aversey commented on src/main/java/assignment/Notifier.java
> +            description = "Succeeded, passed the tests";
Looks like "Failed, compilation failed" needs to be here. Success is to be done in a separate branch.

2023-02-06 20:08 UTC, dengty1998 commented on src/main/java/assignment/Notifier.java
> +            description = "Succeeded, passed the tests";
> Looks like "Failed, compilation failed" needs to be here. Success is to be done in a separate branch.

Ah... I just mistype some code lines. Will fix this

2023-02-06 20:15 UTC, dengty1998 commented
> "set" in the names of functions doesn't seem to be the right word. Don't forget to load secret token from a file (on path "./token"?) and to provide some way for passing the build status and related commit ID to your code (maybe through constructor or method "notify").
> 
> Overall, good work, keep up!

In fact, I just know quite sure about how to get a token(and username) and don't know what kind of data will be sent to me. That's why I create some parameter but leave them empty......:
        String testResult = "";
        String state;
        String targetUrl = "";
        String description;
        String context = "";
        String urlString = "";
        String shaString = "";
        String userString = "";
        String tokenString = "";
And I am not sure about code block in try{} either. Because I have never written a similar function.
So I feel there are still many things that need to be modified...

2023-02-08 21:28 UTC, aversey approved these changes

2023-02-08 21:30 UTC, JonasHUL approved these changes
Well done!!

2023-02-08 21:30 UTC, merged